replicaCount: 1

image:
  repository: dreamthre/waguwau-order-server
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 31163

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ""
      paths:
        - path: /api/v1
          pathType: Prefix
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 100
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 5
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 100
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5
  successThreshold: 1

env:
  - name: "redis"
    value: "waguwagu-redis"
  - name: "SPRING_DATA_MONGODB_URI"
    value: "mongodb://waguwagu-mongo:27017/waguwagu"
  - name: "SPRING_KAFKA_BOOTSTRAP_SERVERS"
    value: "34.71.194.186:9094"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
